### ISSUE TITLE
Try to present something green in a one pager. Create a one pager in general 

### ISSUE THREAD

**Issue by jensamberg** [tqtezos/tezos.com#10]
I am missing some one pager. Or one pictures that tell story’s.
What’s missing 

1. A picture or a statement of the fast transaction
2. A picture of the advantages of the PoS and low energy use of Tezos against PoW

**Comment by paulo60pg** [comment]
A picture is worth a thousand words !

**Comment by jameswjr** [comment]
We are internally working on a media kit and will provide that via the website, so that's our answer to this need.

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
