### ISSUE TITLE
Sign up should send confirm email (was "Sign up for updates still doesn't work ?")

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#15]
I've sign up for updates since you claim the button is fixed.

Didn't received a confirmation email.
Didn't received any update since.

Is this normal ?

**Comment by jameswjr** [comment]
Sign up does not generate a confirmation email.  We'll change that so that it does.

**Comment by jameswjr** [comment]
The signup has been updated to send a confirmation email.  Thank you for bringing this to our attention!
