### ISSUE TITLE
Classify wallets by number of users and not alphabetical order

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#17]
It's kind of stupid to use the alphabetical order to classify wallet.

The number of users should be the metric for this classification.

**Comment by paulo60pg** [comment]
Another idea is that you could classify wallets per feature, for example 
displaying NFT's: yes / no
ability to delegate/stake: yes / no
chrome extension: yes / no

Try to point a new user in the right direction instead of displaying a simple list

**Comment by jameswjr** [comment]
If you have this information and want to have a try at classifying wallets in this way, we would appreciate your contribution.

**Comment by jameswjr** [comment]
Contributions to the website providing this information would be welcome.
