### ISSUE TITLE
Delete job offers from the first page, put this in a separate tab

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#20]
Use the first page to talk about tezos, not job offers !
Add a job offers nav link and put them there.

**Comment by sebuhbitcoin** [comment]
Also add a submission form for smaller projects to submit job listings would be cool. 

It's nice to see which projects have job openings, not just these big companies. Some people may beore comfortable applying to a smaller company to grow with.

**Comment by brennancaldwell** [comment]
Thank you for your suggestions and comments; the teams are actively working on a site redesign to address a lot of the general feedback and we are excited to launch it soon. Once we are able to share more details we will do so.
