### ISSUE TITLE
Integrate new developper portal

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#21]
https://tezos.b9lab.com/
Much better than the one on the site today

By the way any updates on my previous comments ? Site hasn't moved since...

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
