### ISSUE TITLE
Sign up for updates still doesn't work ?

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#22]
I subscribed to the feature many times since you said you fixed it, never received any updade email or confirmation email. Nothing.

**Comment by jameswjr** [comment]
I tested this before I closed the issue, and again just now with a disposable email address, and I received the confirmation both times.  Can you confirm that you used a new email address, and that you checked your spam folders.  I believe a confirmation email is not sent to an already-registered email address, so possibly you are using an email address that's already on the list.

**Comment by paulo60pg** [comment]
I might have used an already signed address. But is it normal I never got any update ? How often are then sent ? I think it's been 2 or 3 years since the first time I signed up. I never received any email since then. No email in 2-3 years. WTF ?

**Comment by jameswjr** [comment]
Thanks for bringing our awareness to this. There are  emails that are  sent  to the distribution list, especially for events like TQuorum, etc. The cadence of emails varies and the teams are looking to further leverage email marketing in the future so stay tuned. Regarding the system functionality, there are no errors or issues, so we are closing this issue out.
