### ISSUE TITLE
Include tezos average transaction fee !

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#23]
The very low transaction fee is a selling point for Tezos.
It would be nice to have an average transaction fee of the network on the first page of the site. This could bring some eth devs and users to the network. This is really an advantage of Tezos over ETH and other smart contract platforms. It's important enough to be on the first page of the site!

**Comment by ankitzm** [comment]
Hey, Can you assign it to me.

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
