### ISSUE TITLE
links to old '/get-started/' URL 404

### ISSUE THREAD

**Issue by saywebsolutions** [tqtezos/tezos.com#24]
There must have previously been a "Getting Started" guide available at https://tezos.com/get-started/ which now returns a 404. It's linked to from the /r/tezos sidebar for instance (and probably more places). You should put a redirect rule in place to the new URL for the guide to maintain search engine rank and avoid breaking existing links.

This is probably happening to other URLs too; is there an analytics suite in place to catch and fix other links that have been broken during the redesign?

**Comment by brennancaldwell** [comment]
Thank you for your input! We've implemented a redirect, and that URL will now point to the proper page.
