### ISSUE TITLE
hello-world carousel arrows on desktop shift

### ISSUE THREAD

**Issue by codingoyster** [tqtezos/tezos.com#27]
so when you click on the carousel arrows (browsing sideways thru images on hello-world), the arrows on the subsequent image shift a little up or down. users shouldn't have to move their mouse to go the next image. fix the positioning of the arrows so they're at a static spot within the carousel, so users do not have to move their mouse.

**Comment by brennancaldwell** [comment]
Thank you for your input. We've updated the UX to make advancing the carousel easier in Desktop.
