### ISSUE TITLE
Please use https://tezos.com/hello-world as landing page

### ISSUE THREAD

**Issue by jensamberg** [tqtezos/tezos.com#31]
Please use https://tezos.com/hello-world as landing page

**Comment by adithyaakrishna** [comment]
@brennancaldwell Is this a valid issue? if so, would like to work on this :)

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
