### ISSUE TITLE
Whitepaper Permalink

### ISSUE THREAD

**Issue by bitc0m** [tqtezos/tezos.com#32]
New site upgrade broke indexed URL on major search engines to the Tezos whitepaper. 
https://tezos.com/assets/files/whitepaper-d0cd272790ed3ba5951b30d019db2013.pdf

**Comment by murbard** [comment]
There should be a test for this in the CI.

**Comment by mathMakesArt** [comment]
Was planning to open a new issue report, but I assume it's related to this one.

The **Tezos Position Paper Permalink** ([https://tezos.com/assets/files/position-paper-00b110d6223dc6b84ac206e92171ed47.pdf](https://tezos.com/assets/files/position-paper-00b110d6223dc6b84ac206e92171ed47.pdf)), as found on [https://wiki.tezosagora.org/positionpaper](https://wiki.tezosagora.org/positionpaper), is broken as well.

**Comment by mathMakesArt** [comment]
In case anyone else stumbles upon this GitHub report before the live site is fixed, here are links to the whitepaper and position paper files within this repository:

[**Whitepaper**](https://github.com/tqtezos/tezos.com/blob/main/static/whitepaper.pdf)

[**Position Paper**](https://github.com/tqtezos/tezos.com/blob/main/static/position-paper.pdf)

**Comment by brennancaldwell** [comment]
Yes, given our migration to Docusaurus, we have had to change file structure. The links above are the new locations of the whitepaper and position paper, respectively. Thank you for pointing this out.
