### ISSUE TITLE
Advertise our DeFi Projects on the webpage to show force of Tezos

### ISSUE THREAD

**Issue by jensamberg** [tqtezos/tezos.com#34]
Advertise our DeFi Projects on the webpage to show force of Tezos

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
