### ISSUE TITLE
Add a "media kit" link

### ISSUE THREAD

**Issue by lousando** [tqtezos/tezos.com#36]
Often projects add a page where they include logo assets, brand colors, and some tips on how to pronounce the name of the project. 

I think adding a page of this sort would help with marketing Tezos ꜩ to more folks.

**Comment by jameswjr** [comment]
Thank you for your suggestion: we appreciate your feedback!  We do intend to add a media kit and this is on our roadmap.

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
