### ISSUE TITLE
Include Timeline of Tezos Upgrades + Countdown to next Upgrade

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#37]
In order for users / new comers to have an overview of Tezos evolution, I suggest we get an interactive timeline on the main page of the site that would display each protocol upgrade and what they brought to Tezos in a few words.

Another idea could be to have a timer to the next upgrade once the adoption period has started in order for bakers to be sure they upgrade their nodes, and for users to build hype around the next protocol upgrade.

**Comment by brennancaldwell** [comment]
Thank you for your suggestions and comments; the teams are actively working on a site redesign to address a lot of the general feedback and we are excited to launch it soon. Once we are able to share more details we will do so.
