### ISSUE TITLE
Boring website

### ISSUE THREAD

**Issue by sebuhbitcoin** [tqtezos/tezos.com#39]
Please add some nice links and basic guides to the best Tezos dapps/projects. 

Some of these come to mind
Baking-bad
Better-call-dev
Temple wallet
Kukai wallet
Hicetnunc
Quipuswap
Salsadao
Tzstats
Tzkt

Why are these amazing projects not on some kind of rotation gallery thingy on the top of the site showing off all the cool stuff built on Tezos.

**Comment by arnaudcisse44** [comment]
I agree, we need a "go to project" tab or showing the tools/dapps on the first page too, and not only the developper side (github, access developer portal) 

tezos.com is the link that ranks first on google search for tezos so it has to bring value to the mass community too. Tezos.help is doing a good job I think, maybe that can be a source of inspiration, or maybe we need a link on the first view of tezos.com that points to tezos.help?

**Comment by japan2k20** [comment]
I agree, we need a "go to project" tab or showing the tools/dapps on the first page too, and not only the developper side (github, access developer portal)

tezos.com is the link that ranks first on google search for tezos so it has to bring value to the mass community too. Tezos.help is doing a good job I think, maybe that can be a source of inspiration, or maybe we need a link on the first view of tezos.com that points to tezos.help?

**Comment by s-m-o-l** [comment]
teztools.io is great

**Comment by Primate411** [comment]
Kolibri.finance and other projects of similar caliber like Crunchy.Network should be on the website. Definitely don't list every shady token project but do show with pride what we do have on Tezos already.

**Comment by sebuhbitcoin** [comment]
A Bakery Listing Like tezos-nodes.com would be very nice also. Categorize each type of baker/node and give a little background story about each Baker so people looking for a baker can easily decide on which baker to go with. 

Bakers are the backbone of Tezos and Tezos-nodes.com and Baking Bad do a great job of showcasing them.

**Comment by sebuhbitcoin** [comment]
Backlinks and SEO optimization to well known projects to help them increase their domains ranking would be amazing. Synergize the projects and help Tezos as a whole grow up.

**Comment by brennancaldwell** [comment]
Thank you for your suggestions and comments; the teams are actively working on a site redesign to address a lot of the general feedback and we are excited to launch it soon. Once we are able to share more details we will do so.

**Comment by japan2k20** [comment]
hi, when could we get a new version of the website? It's been a month and the current website still looks like a landing page for an app that will launch in 2030!

If we want new users, mass adoption etc, we need to get this ecosystem tab so users know where to go to swap, to stake on a DeFi dapp, to borrow money etc please
