### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by codingoyster** [tqtezos/tezos.com#4]
I noticed that the Tezos Discord server isn't linked on the new site footer - it's a great community, way better medium than Telegram. Please update to include an invite link to Discord. Thanks.

**Comment by jameswjr** [comment]
We have been made aware of two different discord servers pertinent to Tezos, this one: https://discord.gg/XRHZgze and this one: https://discord.com/invite/udZwhQn   And there could be others, so this raises the question of how to tell which is the right one to point to in our social links.

**Comment by codingoyster** [comment]
Hey, the second link https://discord.com/invite/udZwhQn is more active, has more users, and is also pinned in Reddit.

**Comment by jameswjr** [comment]
Got it, thanks.  We'll be incorporating a Discord link.

**Comment by jameswjr** [comment]
The link has gone live.
