### ISSUE TITLE
More info for Crypto newbies

### ISSUE THREAD

**Issue by Varstasdp** [tqtezos/tezos.com#51]
I think one of the best ways to get broad adoption is teach new guys how to delegate and advice about supported wallets and safety measures. Your pages seems to be empty, therefore seems like a bad investment from new guys point of view as there is not enough of information.

**Comment by kitarp29** [comment]
Hi, @murbard I would like to work on this issue if you assign it to me?
I am participating in IIITP Hackathon and I want to create a PR under its name. 
Please consider me.

**Comment by wfurnival** [comment]
I am currently stuck in a Tezbox wallet. Would like a wallet that does that 'more'. Texbox also hasn't functioned right for about 6 months.

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
