### ISSUE TITLE
Spotlight the voting system of Tezos 

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#54]
This is THE killing feature of Tezos, we should put it forward. A link to https://www.tezosagora.org/ or to https://tzstats.com/election/head should be included for anyone to understand Tezos democratic evolution.

Talk about the fact that the chain can upgrade every 72 days which is faster than any other chains on the market. It ensures Tezos can adapt fast and is always up to date with the latest technology.

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
