### ISSUE TITLE
Is this the new website ?

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#58]
It's been a few months since some of us started giving feedback on the site. Many issues have been closed, but the website still hasn't moved in months... Are you still patching the old website ? Are you going for a full redesign (that would be good for Tezos) ?
Is it worth it to continue to share some feedback here ?

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
