### ISSUE TITLE
Display community involvement, fellowships offered by tezos, roadmaps and snippets showing handy integrations. 

### ISSUE THREAD

**Issue by lopeselio** [tqtezos/tezos.com#59]
This would leave a good impression on the developer community

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
