### ISSUE TITLE
From Tezos agora : "Add an “Ecosystem” tab on tezos.com website"

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#61]
see full description here : https://forum.tezosagora.org/t/add-an-ecosystem-tab-on-tezos-com-website/3136

**Comment by ankitzm** [comment]
I am working on this, can you please assign it to me.

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit Tezos.com to see the new look+feel and reach out if any suggestions.
