### ISSUE TITLE
Activation Workflow Broken

### ISSUE THREAD

**Issue by covid-l9** [tqtezos/tezos.com#67]
Check and activation pages are being reported as broken. End user claiming they contacted the support email with no response.
https://check.tezos.com
https://activate.tezos.com

**Comment by brennancaldwell** [comment]
We thank you for your suggestions and for flagging this for us. We have recently redesigned and redeployed Tezos.com, taking feedback from the community to help improve the site. The site will continue to evolve and improve - please visit tezos.com to see the new look+feel and reach out if any suggestions.
