### ISSUE TITLE
typo in tezo documentation

### ISSUE THREAD

**Issue by bansalsurya** [tqtezos/tezos.com#68]
Link: https://assets.tqtezos.com/docs/setup/1-tezos-client/

![image](https://user-images.githubusercontent.com/42608756/122956973-1c1f3480-d39f-11eb-913b-82f70f6c9da1.png)

**Comment by adithyaakrishna** [comment]
@bansalsurya I think this issue is in another repo, https://github.com/tqtezos/assets.tqtezos.com
