### ISSUE TITLE
«‎Sign me up»‎ button doesn't work

### ISSUE THREAD

**Issue by ungarson** [tqtezos/tezos.com#8]
Click on the `Sign Up For Updates` button on the main page, then enter a random email and then press the `Sign me up` button.

I get this error in the console:
`Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' <URL> <URL>". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

**Comment by jameswjr** [comment]
Fixed.
