### ISSUE TITLE
Needs more graphical elements !!

### ISSUE THREAD

**Issue by paulo60pg** [tqtezos/tezos.com#9]
Hi there, I've been launching the site on my machine and this is the feedback I can give

1- I think we should have a timeline of the tezos updates (past, in process, future) on the first page of the site. This is what makes Tezos different from all blockchains, it should be displayed right away for people to understand at a glance why Tezos is the best blockchain. This is THE must have of the site imo. 

2- A link to the voting process should be included (Tezos agora or equivalent)

3- The 3 selling points of Tezos are ok, but again, too much text and too few visual explanation. Would be nice to have some interactivity as well on hover. I'm not fond of the icons chosen, which don't bring any value to the text. Homemade design schema could explain better what the text is about.

Happy to discuss this with you

**Comment by paulo60pg** [comment]
Overall I would rather start from scratch and rework the whole website organisation and content with a marketing agency (I'm working with one everyday). They would do a brand new image + website for about 5-10k€ and that would bring much more value to the project than just changing a few things on the existing website, where most features (like newsletter and updates) have never worked in years...

**Comment by jameswjr** [comment]
Thanks for the feedback. As with another issue you raised concerning overall design, these suggestions are fairly broad in scope,  and we’re closing this issue for now, but we will share your feedback with the internal teams.  In the meantime, please continue to feel free to share any specific bug reports or merge requests that we can tackle. Again, thanks so much for taking the time to share your thoughts.
